### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by jtblack-aws** [sbrunner/hooks#146]
The default copyright configuration values in the README appear to have extra characters at the end left over from copying the values from the code.  I believe the correct example default values should be
```yaml
one_date_re: ' Copyright \(c\) (?P<year>[0-9]{4})'
two_date_re: ' Copyright \(c\) (?P<from>[0-9]{4})-(?P<to>[0-9]{4})'
one_date_format: ' Copyright (c) {year}'
two_date_format: ' Copyright (c) {from}-{to}'
license_file: LICENSE
```
