### ISSUE TITLE
Force insert copyright to files

### ISSUE THREAD

**Issue by sgabenov** [sbrunner/hooks#79]
Could you please add description on how to configure pre-commit, so it could force insert copyright LICESE into the commited file the way it is done on checking expired year

**Comment by sbrunner** [comment]
This is not working?
```yaml
repos:
  - repo: https://github.com/sbrunner/hooks
    rev: <version> # Use the ref you want to point at
    hooks:
      # Check that the copyright is present and up to date
      - id: copyright-required
```
